### ISSUE TITLE
Add other Features to the switch-toggles

### ISSUE THREAD

**Issue by beniroquai** [JorisM/Heimdroid#7]
It would be cool to get other API-features in the app as well. I use the RCSwitch via Duino frequently. I have a Temperature Sensor connected to the Duino. Would be nned to have it in the app too :)

**Comment by JorisM** [comment]
RC-Switch feature added. Download version 0.1.3 and pull heimcontrol as soon as this pull request is accepted it should work: https://github.com/ni-c/heimcontrol.js/pull/55

**Comment by beniroquai** [comment]
Absolutely awesom! Thank you so much! :)
