### ISSUE TITLE
My Arduino Uno dont work

### ISSUE THREAD

**Issue by dominikuskoch** [JorisM/Heimdroid#9]
Hi,
it take me days to install heimdroid.js on my rasparrypi. Finaly it works, BUT i cant switch an LED on or of if the LED is pluged into my aruino. Using the gpio pins from Raspberrypi works great.

If I press the on/off switch for the LED in the browser the orange little led (rx) of my adruino blink but nothing happend. 

Please help because i love this projekt very much, thanks Dominikus
Is it nesessery to upload some code to the Adruino ?

**Comment by JorisM** [comment]
I think you want to post this issue on the github page of heimcontroljs? https://github.com/ni-c/heimcontrol.js

This is the git repo for the android app.
